Fixes issues #18 Address content refinement in Scatter Plots > Introduction
google/applied-computing-series pull request #19
Opened 2020-02-12 02:03 UTC by tmadruga

The introduction in scatter plots does not really serve as an introduction to the section as a whole. I have created a new introduction, while renaming the old introduction old introduction.

2020-02-13 20:40 UTC, raskutti requested changes
See comment in #21.

2020-02-17 04:01 UTC, tmadruga commented
@raskutti Changes from PR#21 addressed here.

2020-02-20 14:35 UTC, raskutti requested changes
This is great work, and well written. This review may look like a lot, but it is a lot of very small comments. The overall flow is much better, thank you!

Make sure the book compiles well and all images and links work in Runestone.

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/introduction.rst
> +As of right now, you have learned about histograms and bar charts, which are
"As of right now" feels a bit awkward. Maybe just remove it and say "You have already learned about..."

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/introduction.rst
> +of a larger data set. This is where Scatter plots come in. Scatter plots are a
nit: Don't capitalize "scatter" when it's not the start of the sentence

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/introduction.rst
> +   :alt: An example of a spreadsheet
Alt text should be `An example of a scatter plot`

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +colder closer to the north pole,'' you could say, “as latitude increases by 10
nit: For some reason the end quotes came out as `''` but should be `"`.

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +.. image:: figures/lat_temp_histograms.png
Missing `:align: center`

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +southern cities, and larger latitudes indicate northern cities. See here for a
See where for a map?

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +“Southern,” and Central to more easily analyze the data. Most cities in the
Central is missing quotation marks

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +label cities south of 35 degrees latitude “Southern”, cities north of 40 degrees
Throughout this file, you need to be consistent as to whether you put the commas and periods within the quotes or not. It doesn't matter too much which you choose (there are some examples throughout this whole file), but be consistent.

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +.. image:: figures/city_region_breakdown.png
Missing align

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +Break down these cities into these three separate groups by using the IF
Here and throughout this file, use monospace text for Excel functions such as `IF` and `AVERAGEIF`.

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +.. image:: figures/avg_if.png
Missing align

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +AVERAGEIF function :ref:`(from the section on grouping)<grouping_data>`.
Just making sure that this internal reference works in Runestone?

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +.. image:: figures/avg_temp_region_jan.png
Missing align

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +.. See here for a map of the USA with latitude and longitude lines.: https://pasarelapr.com/images/map-of-usa-with-lines-of-latitude-and-longitude/map-of-usa-with-lines-of-latitude-and-longitude-2.jp
Is this reference missing an underscore?

2020-02-20 14:35 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/motivating_scatterplots.rst
> +.. See here for a map of the USA with latitude and longitude lines.: https://pasarelapr.com/images/map-of-usa-with-lines-of-latitude-and-longitude/map-of-usa-with-lines-of-latitude-and-longitude-2.jp
Do these references work in Runestone? Seems to me like they are missing something to make them work.

2020-02-20 14:35 UTC, raskutti commented
@tmadruga minor changes requested

2020-02-20 19:44 UTC, tmadruga commented
@raskutti changes made.

2020-02-21 17:47 UTC, raskutti approved these changes

2020-02-21 17:48 UTC, merged