Fixes Issued #46
google/applied-computing-series pull request #47
Opened 2020-02-27 19:37 UTC by YBirhane

2020-03-03 23:01 UTC, raskutti requested changes
Overall LGTM. A few minor comments.

2020-03-03 23:01 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/creating_a_scatter_plot_in_sheets.rst
>  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
To be consistent with other files, use the following notation for headings

```
Creating a Scatter Plot in Sheets
=================================
```

2020-03-03 23:01 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/creating_a_scatter_plot_in_sheets.rst
> +In this section, you will learn how to make a scatter plot in Sheets by
Remove "by following along with a tutorial"

2020-03-03 23:01 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/creating_a_scatter_plot_in_sheets.rst
> +First, copy over the city, state, latitude and July mean temperature columns
Blank line after rows of -s

2020-03-03 23:01 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/creating_a_scatter_plot_in_sheets.rst
> +.. image:: figures/create_a_scatter_copy_data.png
Missing :align: center for all images

2020-03-03 23:01 UTC, raskutti commented on ac1/_sources/scatter_plots_and_correlation/creating_a_scatter_plot_in_sheets.rst
> +.. image:: figures/create_a_scatter_vertical_label.png
Blank lines between images

2020-03-04 00:31 UTC, YBirhane commented
@raskutti  everything should be fixed now!

2020-03-04 15:25 UTC, raskutti approved these changes

2020-03-04 15:25 UTC, merged